services:
  postgres:
    image: postgres:16-alpine
    container_name: mogavault-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: mogavault-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_SERVER_JSON_FILE: '/var/lib/pgadmin/servers.json'
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    entrypoint:
      - "/bin/sh"
      - "-c"
      - >
        echo '{
          "Servers": {
            "1": {
              "Name": "MogaVault Local",
              "Group": "Servers",
              "Host": "postgres",
              "Port": 5432,
              "MaintenanceDB": "'"$DB_NAME"'",
              "Username": "'"$DB_USER"'",
              "User": "'"$DB_USER"'",
              "SSLMode": "prefer"
            }
          }
        }' > /var/lib/pgadmin/servers.json && exec /entrypoint.sh
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgdata:
  pgadmin-data: